name: Gitleaks docker

on:
  pull_request:
    branches:
      - main

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Gitleaks and Save Output
        env:
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
        run: |
          echo "Pulling Gitleaks Docker image..."
          docker pull zricethezav/gitleaks:latest
          echo "Running Gitleaks scan..."
          docker run \
            -v ${{ github.workspace }}:/repo \
            -e GITLEAKS_LICENSE=$GITLEAKS_LICENSE \
            zricethezav/gitleaks:latest \
            detect --source=/repo --verbose --report-format=json --report-path=/repo/gitleaks-results.json || true
            
      - name: Comment on PR with Gitleaks Results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Checking if Gitleaks findings exist..."
          
          if [ -f "gitleaks-results.json" ] && [ "$(jq 'length' gitleaks-results.json)" -gt 0 ]; then
            COMMENT="🚨 **Gitleaks Findings:** Potential secrets or vulnerabilities were found. Please review and resolve them before merging."
          else
            COMMENT="✅ **Gitleaks Findings:** No issues were found. Safe to proceed with merge."
          fi
          echo "Posting comment to PR..."
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"body\":\"$COMMENT\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
