name: gitleaks-docker-2

on:
  pull_request:
    branches:
      - main

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Gitleaks and Save Output
        env:
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
        run: |
          echo "Pulling Gitleaks Docker image..."
          docker pull zricethezav/gitleaks:latest
          echo "Running Gitleaks scan..."
          docker run \
            -v ${{ github.workspace }}:/repo \
            -w /repo \
            -e GITLEAKS_LICENSE=$GITLEAKS_LICENSE \
            zricethezav/gitleaks:latest \
            detect --source=. --verbose --exit-code=0 --report-format=json --report-path=gitleaks-results.json || true
          cat gitleaks-results.json
            
      - name: Format and comment findings on PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          FINDINGS_JSON=$(cat gitleaks-results.json)
          COUNT=$(echo "$FINDINGS_JSON" | jq 'length')
          SHA="${{ github.event.pull_request.head.sha }}"
          REPO="${{ github.repository }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          MAX=10
          if [ "$COUNT" -gt 0 ]; then
            COMMENT="**🔐 Gitleaks Findings: $COUNT issue(s) detected**\n\n"
            i=0
            while [ "$i" -lt "$COUNT" ] && [ "$i" -lt "$MAX" ]; do
              ITEM=$(echo "$FINDINGS_JSON" | jq ".[$i]")
              RULE=$(echo "$ITEM" | jq -r '.RuleID')
              DESC=$(echo "$ITEM" | jq -r '.Description')
              FILE=$(echo "$ITEM" | jq -r '.File')
              LINE=$(echo "$ITEM" | jq -r '.StartLine // "unknown"')
              LINK="https://github.com/$REPO/blob/$SHA/$FILE#L$LINE"
              SECRET_MASKED="**********"
              COMMENT+="🔸 **Rule**: \`$RULE\`\n"
              COMMENT+="📄 **File**: \`$FILE:$LINE\`\n"
              COMMENT+="📝 **Description**: $DESC\n"
              COMMENT+="🔑 **Secret**: \`$SECRET_MASKED\`\n"
              COMMENT+="🔗 **Path**: [$FILE:$LINE]($LINK)\n\n"
              i=$((i + 1))
            done
            if [ "$COUNT" -gt "$MAX" ]; then
              COMMENT+="...and more. Only showing first $MAX findings.\n"
            fi
          else
            COMMENT="✅ **Gitleaks Findings:** No secrets detected. Safe to proceed!"
          fi
          # Escape newlines for GitHub API
          COMMENT=$(echo "$COMMENT" | sed ':a;N;$!ba;s/\n/\\n/g')
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"body\":\"$COMMENT\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
