name: gitleaks-docker-2

on:
  pull_request:
    branches:
      - main

jobs:
  gitleaks:
    name: Run Gitleaks on PR Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # required for diffing

      - name: Set PR base and head SHA
        id: sha
        run: |
          echo "BASE_SHA=${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV
          echo "HEAD_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV

      - name: List changed files
        id: changes
        run: |
          git diff --name-only $BASE_SHA $HEAD_SHA > changed_files.txt
          cat changed_files.txt

      - name: Run Gitleaks via Docker on each changed file
        run: |
          mkdir gitleaks-reports
          exit_code=0
          while IFS= read -r file; do
            if [ -f "$file" ]; then
              echo "Scanning $file"
              docker run --rm -v $(pwd):/repo zricethezav/gitleaks:latest detect \
                --source="/repo/$file" \
                --report-path="/repo/gitleaks-reports/$(basename $file).json" \
                --redact \
                --exit-code=0 || true
            fi
          done < changed_files.txt

      - name: Upload Gitleaks Reports
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-reports
          path: gitleaks-reports/
