name: Gitleaks Central workflow foundry

on:
  pull_request:
    branches:
      - main

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  call-gitleaks:
    uses: akashkumarmg/git-central/.github/workflows/Gitleaks Central workflow foundry.yml@main
    secrets: inherit
