name: Gitleaks scan new

on:
  pull_request:
    branches:
      - main

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Download gitleaks.toml
        run: |
          mkdir -p .github
          curl -sSL -o .github/gitleaks.toml https://raw.githubusercontent.com/SkyflowFoundry/.github/main/.github/gitleaks.toml
      - name: Install Gitleaks
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/gitleaks/gitleaks/releases/latest | jq -r .tag_name | sed 's/^v//')
          DOWNLOAD_URL="https://github.com/gitleaks/gitleaks/releases/download/v${LATEST_VERSION}/gitleaks_${LATEST_VERSION}_linux_x64.tar.gz"
          curl -sSL "$DOWNLOAD_URL" -o gitleaks.tar.gz
          tar -xzf gitleaks.tar.gz
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin
          gitleaks version
      - name: Fetch main branch
        run: git fetch origin main
      - name: Scan full main branch
        run: |
          echo "🔍 Scanning full main branch (for log visibility only)..."
          gitleaks git \
            --config=.github/gitleaks.toml \
            --exit-code=0 \
            --report-format=json \
            --report-path=main-results.json \
            --log-opts="origin/main"
          echo "🔎 Main branch scan results:"
          cat main-results.json | jq
      - name: Scan PR commits only
        run: |
          BASE_SHA=$(git merge-base origin/main HEAD)
          HEAD_SHA=$(git rev-parse HEAD)
          echo "🔍 Scanning PR commits: $BASE_SHA..$HEAD_SHA"
          gitleaks git \
            --config=.github/gitleaks.toml \
            --exit-code=0 \
            --report-format=json \
            --report-path=pr-results.json \
            --log-opts="$BASE_SHA..$HEAD_SHA"
          echo "🔎 PR scan results:"
          cat pr-results.json
      
      - name: Format and comment findings on PR
