name: gitleaks-docker-2

on:
  pull_request:
    branches:
      - main

jobs:
  gitleaks:
    name: Run Gitleaks on PR Diff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full history for diffing

      - name: Get PR base and head
        id: pr_info
        run: |
          echo "BASE_SHA=${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV
          echo "HEAD_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV

      - name: Generate PR diff patch
        run: |
          git diff $BASE_SHA $HEAD_SHA > pr.patch

      - name: Run Gitleaks on patch diff (via Docker)
        run: |
          docker run --rm -v $(pwd):/path zricethezav/gitleaks:latest detect \
            --source="/path" \
            --log-opts="-p pr.patch" \
            --report-path="/path/gitleaks-report.json" \
            --exit-code=0
          cat gitleaks-report.json

      - name: Upload Gitleaks report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
