name: Gitleaks secret scan

on:
  workflow_call:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required to access full git history for diff

      - name: Download gitleaks.toml config file
        env:
          GH_TOKEN: ${{ secrets.REPO }}
        run: |
          mkdir -p Rules
          content=$(gh api -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/skyflowapi/.github-private/contents/Rules/gitleaks.toml --jq '.content')
          echo "$content" | base64 -d > Rules/gitleaks.toml

      - name: Determine Gitleaks Scan Range
        id: scan_range
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BASE_SHA="${{ github.event.pull_request.base.sha }}"
            HEAD_SHA="${{ github.event.pull_request.head.sha }}"
            echo "Scanning changes between $BASE_SHA and $HEAD_SHA"
            echo "log_opts=--log-opts=--patch=$BASE_SHA...$HEAD_SHA" >> $GITHUB_OUTPUT
          else
            echo "Scanning working tree only"
            echo "log_opts=--log-opts=--since=1.day" >> $GITHUB_OUTPUT
          fi

      - name: Run Gitleaks Scan
        env:
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS }}
        run: |
          echo "Pulling Gitleaks Docker image..."
          docker pull zricethezav/gitleaks:latest
          echo "Running Gitleaks scan with dynamic log_opts..."
          docker run \
            -v ${{ github.workspace }}:/repo \
            -e GITLEAKS_CONFIG=/repo/Rules/gitleaks.toml \
            -e GITLEAKS_LICENSE=$GITLEAKS \
            zricethezav/gitleaks:latest \
            detect --source=/repo --verbose --config=$GITLEAKS_CONFIG \
            ${{ steps.scan_range.outputs.log_opts }} \
            --exit-code=0 --report-format=json --report-path=/repo/gitleaks-results.json || true

      - name: Format and comment findings on PR
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
        run: |
          FINDINGS_JSON=$(cat gitleaks-results.json)
          COUNT=$(echo "$FINDINGS_JSON" | jq 'length')
          SHA="${{ github.event.pull_request.head.sha }}"
          REPO="${{ github.repository }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          MAX=10
          if [ "$COUNT" -gt 0 ]; then
            COMMENT="**🔐 Gitleaks Findings: $COUNT issue(s) detected**\n\n"
            i=0
            while [ "$i" -lt "$COUNT" ] && [ "$i" -lt "$MAX" ]; do
              ITEM=$(echo "$FINDINGS_JSON" | jq ".[$i]")
              RULE=$(echo "$ITEM" | jq -r '.RuleID')
              DESC=$(echo "$ITEM" | jq -r '.Description')
              FILE=$(echo "$ITEM" | jq -r '.File')
              LINE=$(echo "$ITEM" | jq -r '.Line')
              LINK="https://github.com/$REPO/blob/$SHA/$FILE#L$LINE"
              SECRET_MASKED="**********"
              COMMENT+="🔸 **Rule**: \`$RULE\`\n"
              COMMENT+="📄 **File**: \`$FILE:$LINE\`\n"
              COMMENT+="📝 **Description**: $DESC\n"
              COMMENT+="🔑 **Secret**: \`$SECRET_MASKED\`\n"
              COMMENT+="🔗 **Path**: [$FILE:$LINE]($LINK)\n\n"
              i=$((i + 1))
            done
            if [ "$COUNT" -gt "$MAX" ]; then
              COMMENT+="...and more. Only showing first $MAX findings.\n"
            fi
          else
            COMMENT="✅ **Gitleaks Findings:** No secrets detected. Safe to proceed!"
          fi
          COMMENT=$(echo "$COMMENT" | sed ':a;N;$!ba;s/\n/\\n/g')
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"body\":\"$COMMENT\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
