name: Gitleaks secret scan

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Gitleaks and Save Output
        env:
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Pulling Gitleaks Docker image..."
          docker pull zricethezav/gitleaks:latest
          echo "Running Gitleaks scan..."
          CHANGED_FILES=$(git diff --name-only --diff-filter=ACMRTUXB ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          FINDINGS=""
          for file in $CHANGED_FILES; do
            if [ -f "$file" ]; then
              docker run \
                -v ${{ github.workspace }}:/path \
                -e GITLEAKS_LICENSE=$GITLEAKS_LICENSE \
                zricethezav/gitleaks:latest \
                detect --source=/path/$file --verbose  --exit-code=0 --report-format=json | jq '.[] | .RuleID, .Description, .File, .Line' > findings.json || true
              if [ -s findings.json ]; then
                FINDINGS+="**File: $file**\n"
                while IFS= read -r line; do
                  FINDINGS+="$line\n"
                done < findings.json
              fi
            fi
          done
          if [ -n "$FINDINGS" ]; then
            COMMENT="** Gitleaks Findings:**\n\n$FINDINGS"
          else
            COMMENT="✅ **Gitleaks Findings:** No secrets detected. Safe to proceed!"
          fi
          COMMENT=$(echo "$COMMENT" | sed ':a;N;$!ba;s/\n/\\n/g')
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"body\":\"$COMMENT\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
