name: gitleaks-try-1
on: [push, pull_request, workflow_dispatch]

jobs:
  scan:
    name: gitleaks-try-1
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}
          GITLEAKS_CONFIG: ${{ github.workspace }}/.github/gitleaks.toml
