name: Semgrep-new

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # Write permission to add comments on PRs
      issues: write         # Write permission to add comments to PRs
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Semgrep and jq
        run: |
          python3 -m venv .venv
          .venv/bin/pip install semgrep jq

      - name: Run Semgrep
        run: |
          source .venv/bin/activate
          semgrep --config auto --json-output=results.json --no-error
          jq .results results.json > pretty-results.json

      - name: Display Raw Semgrep JSON Output
        run: |
          echo "Displaying raw Semgrep results..."
          cat pretty-results.json

      - name: Add comment on PR if findings are found
        uses: actions/github-script@v6
        with:
          script: |
            // Ensure the context has a pull_request
            if (context.payload.pull_request) {
              const prNumber = context.payload.pull_request.number;
              const fs = require('fs');
              
              // Read the pretty JSON results
              const results = JSON.parse(fs.readFileSync('pretty-results.json', 'utf8'));

              // Initialize a count for severity levels
              let severityCount = 0;

              // Search for "severity" values in the JSON
              results.forEach(issue => {
                if (issue.severity === 'WARNING') {
                  severityCount++;
                }
              });

              // Log the severity count
              console.log(`Found ${severityCount} high-severity findings.`);

              // Prepare the PR comment body
              let commentBody = '';
              if (severityCount > 0) {
                commentBody = `**Semgrep-new Findings:** Vulnerabilities are found in the code. Please address them before merging.`;
              } else {
                commentBody = "**Semgrep-new Findings:** No issues found, good to merge.";
              }

              // Add the comment to the PR
              await github.rest.issues.createComment({
                ...context.repo,
                issue_number: prNumber,
                body: commentBody
              });
            } else {
              console.log("This workflow wasn't triggered by a pull request, so no comment will be added.");
            }
