name: Semgrep

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Give write permission to PRs
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Semgrep and jq
        run: |
          sudo apt install python3-venv jq
          python3 -m venv .venv
          .venv/bin/pip install semgrep
      - name: Run Semgrep
        run: |
          source .venv/bin/activate
          semgrep --config auto --severity WARNING --json-output=results.json --no-error
          cat results.json | jq .results > pretty-results.json
      - name: Display Raw Semgrep JSON Output
        run: |
         echo "Displaying raw Semgrep results..."
         cat pretty-results.json
         
      - name: Add comment on PR if findings are found
        run: |
          # Set the severity level dynamically (e.g., "WARNING", "ERROR", "INFO")
          SEVERITY_LEVEL="WARNING"  # Modify this to adjust severity level, default is "WARNING"

          # Search for the specified severity in the pretty-results.json file
          if grep -q "\"severity\": \"$SEVERITY_LEVEL\"" pretty-results.json; then
            echo "Semgrep findings: Issues with $SEVERITY_LEVEL level severity are found, Please resolve the issues before merging."
            COMMENT="**Semgrep findings**: Issues with $SEVERITY_LEVEL level severity are found, Please resolve the issues before merging."
          else
            echo "No $SEVERITY_LEVEL level issues found, Good to merge."
            COMMENT="**Semgrep findings**: No $SEVERITY_LEVEL level issues found, Good to merge."
          fi

          # Comment on the PR
          prNumber=${{ github.event.pull_request.number }}
          gh pr comment $prNumber --body "$COMMENT"
